[KLO-19] feat: last update for commit message convention

diff --git a/.github/workflows/branch-and-commit-check.yml b/.github/workflows/branch-and-commit-check.yml
--- a/.github/workflows/branch-and-commit-check.yml
+++ b/.github/workflows/branch-and-commit-check.yml
@@ -23,10 +23,18 @@ jobs:
             exit 1
           fi
 
-      - name: Validate commit message
+      - name: Validate commit messages
         run: |
-          COMMIT_MSG=$(git log -1 --pretty=%B)
-          if ! [[ "$COMMIT_MSG" =~ ^[A-Z]+-[0-9]+ ]]; then
-            echo "Error: Commit message must start with a Jira ticket (e.g., PROJ-1234)."
-            exit 1
-          fi
+          COMMITS=$(curl -s \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" | \
+            jq -r '.[].commit.message')
+
+          IFS=$'\n'  # Set the internal field separator to handle each commit message as a whole
+          for COMMIT_MSG in $COMMITS; do
+            echo "Commit Message: $COMMIT_MSG"
+            if ! [[ "$COMMIT_MSG" =~ ^\[[A-Z]+-[0-9]+\] ]]; then
+              echo "Error: Commit message must start with a Jira ticket in the format '[PROJ-1234]'."
+              exit 1
+            fi
+          done
